export const ADD_TASK = 'ADD_TASK'
export const GET_TASKS = 'GET_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const COMPLETE_TASK = 'COMPLETE_TASK' //Complete and uncomplete both
export const SET_EDIT_TASK = 'SET_EDIT_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const ADD_TAG = 'ADD_TAG'
export const LOAD_TAGS = 'LOAD_TAGS'
export const SET_TAG = 'SET_TAG'